name: Scan Repository

on:
  push:
    branches:
      - main

jobs:
  scan-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Fetch all files
      id: fetch-files
      run: |
        files=$(find . -type f | sed 's|./||' | grep -v "^\.git/")
        echo "FILES=$files" >> $GITHUB_ENV
        echo "::set-output name=files::$files"

    - name: Scan
      uses: Lirancj/project@v1
      with:
        files: ${{ steps.fetch-files.outputs.files }}
