name: Scan Repository

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  scan-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch all files
      id: fetch-files
      run: |
        all_files=$(find . -type d -name '.*' -prune -o ! -name '.*' -type f -print | tr '\n' ' ')
        echo "Files: $all_files"
        echo "::set-output name=files::$all_files"

    - name: Scan
      uses: Lirancj/project@v1
      with:
        files: ${{ steps.fetch-files.outputs.files }}
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}
