name: Scan Repository

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  scan-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch all files
      id: fetch-files
      run: |
        all_files=$(find . -type f | grep -v '/\.' | tr '\n' ' ')
        echo "Files: $all_files"
        echo "::set-output name=files::$all_files"

    - name: Scan
      uses: Lirancj/project@v1
      with:
        files: ${{ steps.fetch-files.outputs.files }}
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}
      id: scan_step

    - name: Revert Push on Scan Failure
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
      if: failure()
      run: |
        git config --global user.name "Leon Detector Bot"
        git config --global user.email "actions@github.com"
        git revert HEAD --no-edit
        git push origin main

