name: Scan Repository

on:
  push:
    branches:
      - main

jobs:
  scan-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Fetch all files
      id: fetch-files
      run: |
        files=$(find . -type f | sed 's|./||' | grep -v "^\.git/")
        files_json=$(echo "$files" | jq -R -s -c 'split("\n")[:-1]')
        echo "FILES_JSON=$files_json" >> $GITHUB_ENV
        echo "::set-output name=files::$files_json"


    - name: Scan
      uses: Lirancj/project@v1
      with:
        files: ${{ steps.fetch-files.outputs.files }}
